### PR TITLE
#134: Fixed missing code name in changes_x.x.x.md template

### LINKED ISSUE #134: Code name missing in changes_x.x.x.md template
The template for changes_x.x.x.md does not contain the required `Code name:` section.

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #134

### CODE REVIEW

File: src/main/java/com/exasol/projectkeeper/validators/changesfile/ChangesFileValidator.java [hunk 1]
```diff
@@ -99,7 +99,7 @@ private ChangesFile fixSections(final ChangesFile changesFile) {
     private ChangesFile getTemplate() {
         final var changesFile = ChangesFile.builder()
                 .setHeader(List.of("# " + this.projectName + " " + this.projectVersion + ", released "
-                        + LocalDateTime.now().getYear() + "-??-??", ""))//
+                        + LocalDateTime.now().getYear() + "-??-??", "", "Code name:", ""))//
```
Comment (AnastasiiaSergienko) [inline src/main/java/com/exasol/projectkeeper/validators/changesfile/ChangesFileValidator.java:102]: Will the code name be placed on a new line?

Comment (jakobbraun) [reply src/main/java/com/exasol/projectkeeper/validators/changesfile/ChangesFileValidator.java:102]: yes. Each element in the list is a line.

**Review by AnastasiiaSergienko — APPROVED** [review]
