### PR TITLE
#106: Fixed sonar security hotspots

### LINKED ISSUE #106: Fix sonar security hotspots

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #106

### CODE REVIEW

File: src/main/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidator.java [hunk 1]
```diff
@@ -130,15 +126,29 @@ private FileTemplate(final Resource template, final TemplateType type, final Str
 
         public static FileTemplate fromResource(final Resource templateResource) {
             final String resourceName = templateResource.getURI().toString();
-            final Matcher matcher = TEMPLATE_NAME_PATTERN.matcher(resourceName);
-            if (!matcher.matches()) {
+            final Path resourcePath = Path.of(resourceName);
+            final int templatesFolderIndex = getTemplatesFolderIndex(resourcePath);
+            if (templatesFolderIndex == -1 || resourcePath.getNameCount() - templatesFolderIndex < 3) {
```
Comment (AnastasiiaSergienko) [inline src/main/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidator.java:131]: Maybe extract a validation method?

**Review by AnastasiiaSergienko — APPROVED** [review]
Approved with one suggestion
