### PR TITLE
bug/256: Fixed that changelog file was only updated on second run

### LINKED ISSUE #256: Change log file is only fixed on second run
PK only adds the current version to the changelog file after running fix twice.

Reason:
In the first run it adds the changes file, in the second it detects it and adds it to the changelog.
This is bug was introduced with 2.0.0 since starting from that version we first run all validations of a phase and then fix all errors at once.
By that the changelog validator can not yet see the new changes file.

### LINKED ISSUE #258: Clean up non generated poms
Remove the declarations that are already in the `pk_generated.pom`s from the `pom.xml` files.

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #256 
Closes #258

### CODE REVIEW

File: project-keeper/src/main/java/com/exasol/projectkeeper/ProjectKeeper.java [hunk 1]
```diff
@@ -179,12 +191,14 @@ public boolean fix() {
      * @return {@code true} if all {@link PhaseResultHandler} returned {@code true}. {@code false otherwise}
      */
     private boolean runValidationPhases(final PhaseResultHandler phaseResultHandler) {
-        final List<ValidationFinding> phase1Findings = runValidation(getPhase1Validators());
-        if (!phaseResultHandler.handlePhaseResult(phase1Findings)) {
-            return false;
+        for (final Supplier<List<Validator>> phaseSupplier : getValidatorChain()) {
+            final List<Validator> validators = phaseSupplier.get();
+            final List<ValidationFinding> phase1Findings = runValidation(validators);
+            if (!phaseResultHandler.handlePhaseResult(phase1Findings)) {
```
Comment (kaklakariada) [inline project-keeper/src/main/java/com/exasol/projectkeeper/ProjectKeeper.java:197]:
```suggestion
            final List<ValidationFinding> findings = runValidation(validators);
            if (!phaseResultHandler.handlePhaseResult(findings)) {
```

**Review by kaklakariada — CHANGES_REQUESTED** [review]

**Review by kaklakariada — APPROVED** [review]
