### PR TITLE
Bugfix #218: Fix windows build

### LINKED ISSUE #218: Fix windows build
Currently, windows-build fails since it can't find `mvn`. Maybe we need to run `mvn.bat`.

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #218

### CODE REVIEW

File: project-keeper/src/main/java/com/exasol/projectkeeper/AsyncStreamReader.java [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+import java.util.logging.Logger;
+
+import com.exasol.errorreporting.ExaError;
+
+/**
+ * This class starts a new {@link Thread} that reads from an {@link InputStream} and forwards the input line by line to
+ * a given {@link Consumer}.
+ */
+class AsyncStreamReader {
+
```
Comment (jakobbraun) [inline project-keeper/src/main/java/com/exasol/projectkeeper/AsyncStreamReader.java:21]:
```suggestion
```

File: project-keeper/src/main/java/com/exasol/projectkeeper/AsyncStreamReader.java [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+                    exception);
+        }
+    }
+
+    static class CollectingConsumer implements Consumer<String> {
+        private final StringBuilder stringBuilder = new StringBuilder();
+
+        @Override
+        public void accept(String line) {
+            LOGGER.fine(() -> "OUTPUT> " + line);
```
Comment (jakobbraun) [inline project-keeper/src/main/java/com/exasol/projectkeeper/AsyncStreamReader.java:73]: Do we need this log? If not you could replace this class with stringBuilder::add

File: project-keeper/src/main/java/com/exasol/projectkeeper/JavaProjectCrawlerRunner.java [hunk 3]
```diff
@@ -58,38 +59,40 @@ public ProjectDependencies getDependencies(final Path pomFile) {
...
-                LOGGER.log(Level.SEVERE, errors);
                 throw new IllegalStateException(ExaError.messageBuilder("E-PK-CORE-81")
-                        .message("Timeout while executing project-keeper-java-project-crawler.").toString());
+                        .message("Timeout while executing command {{executed command|uq}}. Output was {{output}}",
+                                commandParts, streamConsumer.toString())
+                        .toString());
             }
             final int exitCode = proc.exitValue();
-            final String output = readFromStream(proc.getInputStream());
+            final String output = streamConsumer.toString();
```
Comment (jakobbraun) [inline project-keeper/src/main/java/com/exasol/projectkeeper/JavaProjectCrawlerRunner.java:82]: I think the consumer sould wait until the stream is closed. Here we should wait for the reader to signal that via a mutex. Otherwise, it could happen that the reader was not scheduled recently and did not read everything.

**Review by jakobbraun — CHANGES_REQUESTED** [review]

File: project-keeper/src/main/java/com/exasol/projectkeeper/AsyncStreamReader.java (hunk 2 above)
Comment (kaklakariada) [reply project-keeper/src/main/java/com/exasol/projectkeeper/AsyncStreamReader.java:72]: I would like to keep the log for debugging purposes. But I changed the level to `finest`.

File: project-keeper/src/main/java/com/exasol/projectkeeper/JavaProjectCrawlerRunner.java (hunk 3 above)
Comment (kaklakariada) [reply project-keeper/src/main/java/com/exasol/projectkeeper/JavaProjectCrawlerRunner.java]: Good point. I refactored the code to wait until the stream is closed.

File: project-keeper/src/main/java/com/exasol/projectkeeper/stream/CollectingConsumer.java [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+    }
+
+    /**
+     * Waits until the stream was read completely and returns the read content from the stream.
+     * 
+     * @param timeout the maximum time to wait
+     * @return the content collected from the stream
+     * @throws InterruptedException if the current thread is interrupted while waiting
+     */
+    public String getContent(Duration timeout) throws InterruptedException {
```
Comment (jakobbraun) [inline project-keeper/src/main/java/com/exasol/projectkeeper/stream/CollectingConsumer.java:40]: :+1:

**Review by jakobbraun — APPROVED** [review]
