### PR TITLE
#125: Fixed sonar findings

### LINKED ISSUE #125: Handle securitry hotspot
Sonar shows a false-positive security hotspot.

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #125

### CODE REVIEW

File: src/main/java/com/exasol/projectkeeper/validators/changesfile/TemporaryPomFile.java [hunk 1]
```diff
@@ -0,0 +1,52 @@
+package com.exasol.projectkeeper.validators.changesfile;
+
+import java.io.IOException;
+import java.nio.file.*;
+
+import com.exasol.errorreporting.ExaError;
+
+/**
+ * This class temporary saves a pom file so that it can be parsed by the
```
Comment (morazow) [inline src/main/java/com/exasol/projectkeeper/validators/changesfile/TemporaryPomFile.java:9]:
```suggestion
 * This class temporarily saves a pom file so that it can be parsed by the
```

File: src/main/java/com/exasol/projectkeeper/validators/changesfile/TemporaryPomFile.java [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+     * 
+     * @param content pom file content
+     */
+    public TemporaryPomFile(final String content) {
+        try {
+            this.pomFile = Files.createTempFile("pom-file-cache", ".xml");
+            Files.writeString(this.pomFile, content, StandardOpenOption.TRUNCATE_EXISTING);
+        } catch (final IOException exception) {
+            throw new IllegalStateException(
+                    ExaError.messageBuilder("E-PK-58").message("Failed to temporary store pom file on disk.")
```
Comment (morazow) [inline src/main/java/com/exasol/projectkeeper/validators/changesfile/TemporaryPomFile.java:26]:
```suggestion
                    ExaError.messageBuilder("E-PK-58").message("Failed to temporarily store pom file on disk.")
```

File: src/main/java/com/exasol/projectkeeper/validators/changesfile/TemporaryPomFile.java [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+        } catch (final IOException exception) {
+            throw new IllegalStateException(
+                    ExaError.messageBuilder("E-PK-59").message("Failed to remove temporary cache file.")
+                            .mitigation("Check the file permissions.").toString(),
+                    exception);
+        }
+    }
+
+    /**
+     * Get the path of the pom file on disc.
```
Comment (morazow) [inline src/main/java/com/exasol/projectkeeper/validators/changesfile/TemporaryPomFile.java:45]:
```suggestion
     * Get the path of the pom file on disk.
```

**Review by morazow — APPROVED** [review]
Approved with minor edits.
