### PR TITLE
#87: Fixed failing dependency section validation after release

### LINKED ISSUE #87: Changes file dependency section validation will fail after release
Currently the dependency section validation checks for the latest release. After release, this might be the same as the current version --> different dependency updates.

Solution:
Exclude the current version when searching for the previous release.

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #87

### CODE REVIEW

File: src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java [hunk 1]
```diff
@@ -189,6 +187,22 @@ void testChangesFileGeneration() throws IOException, GitAPIException, Verificati
                         containsString("* Updated `org.apache.maven.plugins:maven-surefire-plugin:2.12.4` to")));
     }
 
+    private void setupDemoProjectWithDependencyChange(final boolean released) throws IOException, GitAPIException {
+        final Git git = Git.open(this.projectDir.toFile());
+        writePomWithOneDependency("0.1.0", "1.0.0");
+        makeRelease(git, "0.1.0");
+        writePomWithOneDependency("0.2.0", "1.0.1");
+        if (released) {
+            makeRelease(git, "0.2.0");
```
Comment (AnastasiiaSergienko) [inline src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java:196]: I think git doesn't have a 'release' concept, maybe we can rename the methods to addTag?

**Review by AnastasiiaSergienko — APPROVED** [review]
Approved with a small suggestion

File: src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java (hunk 1 above)
Comment (jakobbraun) [reply src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java]: :+1:
