### PR TITLE
#131: Fixed dependency crawling for artifact that are not on maven central

### LINKED ISSUE #131: Dependency crawling fails if artifact is not on maven central
Example: exasol-testcontainers

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #131

### CODE REVIEW

File: src/main/java/com/exasol/projectkeeper/pom/MavenArtifactModelReader.java [hunk 1]
```diff
@@ -1,22 +1,53 @@
...
+    private final RepositorySystem repositorySystem;
+
+    /**
+     * Create a new instance of {@link MavenArtifactModelReader}.
+     * 
+     * @param mavenProjectBuilder maven project builder
+     * @param session             maven session
+     * @param repositorySystem    maven repository system
+     */
+    public MavenArtifactModelReader(final ProjectBuilder mavenProjectBuilder, final MavenSession session,
```
Comment (AnastasiiaSergienko) [inline src/main/java/com/exasol/projectkeeper/pom/MavenArtifactModelReader.java:28]: What is the artifact model? 
"An artifact is a file, usually a JAR, that gets deployed to a Maven repository."

Is the model a description of a specified JAR file?

File: src/main/java/com/exasol/projectkeeper/validators/changesfile/DependencySectionFixer.java [hunk 2]
```diff
@@ -26,16 +26,16 @@
...
         this.mavenModelReader = mavenModelReader;
         this.projectDirectory = projectDirectory;
         this.currentMavenModel = parseCurrentPomFile(projectDirectory.resolve("pom.xml"));
     }
 
     private Model parseCurrentPomFile(final Path pomFile) {
         try {
-            return this.mavenModelReader.readModel(pomFile.toFile());
-        } catch (final MavenFileModelReader.ReadFailedException exception) {
+            return this.mavenModelReader.readModel(pomFile.toFile()).getModel();
```
Comment (AnastasiiaSergienko) [inline src/main/java/com/exasol/projectkeeper/validators/changesfile/DependencySectionFixer.java:37]: I expect that readModel() returns model, but we have to also call getModel() afterward. Renaming should fix it

File: src/main/java/com/exasol/projectkeeper/validators/dependencies/ProjectDependencyReader.java [hunk 3]
```diff
@@ -40,8 +41,9 @@ public ProjectDependencyReader(final MavenFileModelReader fileModelReader,
      * @return list of dependencies
      */
     public List<ProjectDependency> readDependencies(final File pomFile) {
-        final var model = parsePomFile(pomFile);
-        return getDependenciesIncludingPlugins(model).map(this::getDependenciesLicense).collect(Collectors.toList());
+        final var project = parsePomFile(pomFile);
```
Comment (AnastasiiaSergienko) [inline src/main/java/com/exasol/projectkeeper/validators/dependencies/ProjectDependencyReader.java:44]: Would be nice to rename it to `createProjectFromPom` or something like this

File: src/main/java/com/exasol/projectkeeper/validators/dependencies/ProjectDependencyReader.java [hunk 4]
```diff
@@ -40,8 +41,9 @@ public ProjectDependencyReader(final MavenFileModelReader fileModelReader,
...
+        return getDependenciesIncludingPlugins(project.getModel())
```
Comment (AnastasiiaSergienko) [inline src/main/java/com/exasol/projectkeeper/validators/dependencies/ProjectDependencyReader.java:45]: I think it would be more clear to get plugins and dependencies separately and then merge them instead of doing magic inside `getDependenciesIncludingPlugins` method

File: src/main/java/com/exasol/projectkeeper/validators/dependencies/ProjectDependencyReader.java [hunk 5]
```diff
@@ -58,10 +60,10 @@ private Dependency convertPluginToDependency(final Plugin plugin) {
         return dependency;
     }
 
-    private ProjectDependency getDependenciesLicense(final Dependency dependency) {
+    private ProjectDependency getDependenciesLicense(final Dependency dependency, final MavenProject project) {
```
Comment (AnastasiiaSergienko) [inline src/main/java/com/exasol/projectkeeper/validators/dependencies/ProjectDependencyReader.java:63]:
```suggestion
    private ProjectDependency getLicense(final Dependency dependency, final MavenProject project) {
```

Comment (AnastasiiaSergienko) [inline src/main/java/com/exasol/projectkeeper/validators/dependencies/ProjectDependencyReader.java:63]: Maybe sent repositories to this method instead of MavenProject?

File: src/test/java/com/exasol/projectkeeper/validators/dependencies/DependenciesValidatorIT.java [hunk 6]
```diff
@@ -40,6 +41,17 @@ void testWrongContent() throws IOException, VerificationException {
         assertThat(output, containsString("[ERROR] E-PK-53: The dependencies.md file has outdated content."));
     }
 
+    @Test
+    void testWrongContentWithNonDefaultRepository() throws IOException, VerificationException {
```
Comment (AnastasiiaSergienko) [inline src/test/java/com/exasol/projectkeeper/validators/dependencies/DependenciesValidatorIT.java:45]: Can you also test that the link was extracted and written to the dependencies file from a non-default repository?

**Review by AnastasiiaSergienko — CHANGES_REQUESTED** [review]
It's great to have this fix! I left a few comments

File: src/main/java/com/exasol/projectkeeper/validators/dependencies/ProjectDependencyReader.java (hunk 4 above)
Comment (jakobbraun) [reply src/main/java/com/exasol/projectkeeper/validators/dependencies/ProjectDependencyReader.java:45]: well, that's what the method does. I thought it would be good to move it to a method and give it a name, since it not very readable otherwise.

File: src/main/java/com/exasol/projectkeeper/validators/dependencies/ProjectDependencyReader.java (hunk 5 above)
Comment (jakobbraun) [reply src/main/java/com/exasol/projectkeeper/validators/dependencies/ProjectDependencyReader.java:63]: I like it like that, since it keeps the abstraction layer of `readDependencies` higher

File: src/test/java/com/exasol/projectkeeper/validators/dependencies/DependenciesValidatorIT.java (hunk 6 above)
Comment (jakobbraun) [reply src/test/java/com/exasol/projectkeeper/validators/dependencies/DependenciesValidatorIT.java:45]: the difference between non-default and default is only in the crawler module. Unfortunately, I can't unit test it, since it depends on injected maven dependencies. As long as the repository is discovered the is no different path to cover.
(Integration tests are time expensive here...)

File: src/main/java/com/exasol/projectkeeper/validators/dependencies/ProjectDependencyReader.java (hunk 3 above)
Comment (jakobbraun) [reply src/main/java/com/exasol/projectkeeper/validators/dependencies/ProjectDependencyReader.java:44]: this method reads the dependencies of a project. So I think the name fits. It uses the project to get it, but that's implementation detail

File: src/main/java/com/exasol/projectkeeper/AbstractProjectKeeperMojo.java [hunk 7]
```diff
@@ -76,8 +75,8 @@
         final var brokenLinkReplacer = new BrokenLinkReplacer(this.linkReplacements);
         final Set<ProjectKeeperModule> enabledModules = getEnabledModules();
         final var excludedFilesMatcher = new ExcludedFilesMatcher(this.excludedFiles);
-        final var mavenModelReader = new DefaultMavenFileModelReader(this.mavenProjectBuilder, this.session);
-        final MavenArtifactModelReader artifactReader = new DefaultMavenArtifactModelReader(this.mavenProjectBuilder,
+        final var mavenModelReader = new DefaultMavenFileProjectReader(this.mavenProjectBuilder, this.session);
```
[the remark this answers is not in the document]
Comment (jakobbraun) [reply src/main/java/com/exasol/projectkeeper/AbstractProjectKeeperMojo.java:78]: I tried to improve

File: doc/changes/changes_0.7.2.md [hunk 8]
```diff
@@ -0,0 +1,26 @@
+# Project keeper maven plugin 0.7.2, released 2021-06-08
```
Comment (AnastasiiaSergienko) [inline doc/changes/changes_0.7.2.md:1]: Please, update the release date

**Review by AnastasiiaSergienko — APPROVED** [review]
I like new names better :+1:

File: doc/changes/changes_0.7.2.md (hunk 8 above)
Comment (jakobbraun) [reply doc/changes/changes_0.7.2.md:1]:
```suggestion
# Project keeper maven plugin 0.7.2, released 2021-06-09
```
