### PR TITLE
#74: Fixed a bug that the project was only valid after running fix twice

### LINKED ISSUE #74: Project only valid after running fix twice
In some situations, it is required to run fix twice in order to make the validation pass. 
This is caused by a design issue that the changes of the pom fixing are written after all other fixes.
By that, the dependency declarations miss the plugins that were added during pom fixing.

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #74

### CODE REVIEW

File: src/main/java/com/exasol/projectkeeper/validators/pom/PomFileValidator.java [hunk 1]
```diff
@@ -20,23 +22,44 @@
...
         ALL_VALIDATORS.stream().filter(validator -> this.enabledModules.contains(validator.getModule())).forEach(
-                template -> template.validate(this.pomFile.getContent(), this.enabledModules, findingConsumer));
+                template -> template.validate(this.pomFileIO.getContent(), this.enabledModules, findings::add));
+        if (!findings.isEmpty()) {
+            getCompoundFinding(findingConsumer, findings);
+        }
         return this;
     }
+
+    private void getCompoundFinding(final Consumer<ValidationFinding> findingConsumer,
```
Comment (AnastasiiaSergienko) [inline src/main/java/com/exasol/projectkeeper/validators/pom/PomFileValidator.java:49]: Can you please extract small methods here to improve readability?

**Review by AnastasiiaSergienko — APPROVED** [review]
Approve with a small suggestion
