### PR TITLE
Bug/119 Fixed windows compatibility issues

### LINKED ISSUE #119: Fix windows compatibility issues
On Windows PK want's to change the files since they have different line endings.

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #119

### CODE REVIEW

File: src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java [hunk 1]
```diff
@@ -180,12 +184,13 @@ void testChangesFileGeneration(final boolean released) throws IOException, GitAP
     }
 
     private void setupDemoProjectWithDependencyChange(final boolean released) throws IOException, GitAPIException {
-        final Git git = Git.open(this.projectDir.toFile());
-        writePomWithOneDependency("0.1.0", "0.1.0");
-        commitAndMakeTag(git, "0.1.0");
-        writePomWithOneDependency("0.2.0", "0.2.0");
-        if (released) {
-            commitAndMakeTag(git, "0.2.0");
+        try (final Git git = Git.open(this.projectDir.toFile())) {
```
Comment (pj-spoelders) [inline src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java:187]: Just curious, why did you wrap this in a try block?

**Review by pj-spoelders — APPROVED** [review]

File: src/main/java/com/exasol/projectkeeper/ExcludedFilesMatcher.java [hunk 2]
```diff
@@ -26,7 +26,7 @@ public ExcludedFilesMatcher(final Collection<String> excludedFilePatterns) {
     }
 
     private static String removeTrailingSlash(final String fileName) {
-        if (fileName.startsWith(FILE_SYSTEM.getSeparator())) {
+        if (fileName.startsWith("/")) {
```
[the remark this answers is not in the document]
Comment (jakobbraun) [reply src/main/java/com/exasol/projectkeeper/ExcludedFilesMatcher.java:29]: In that case, it is indeed intended that it is always the `/`.
Reason: The input is a configuration from the pom file. Since the pom file is always the same I decided that we're using forward slashed there.

File: src/test/java/com/exasol/projectkeeper/validators/dependencies/DependenciesValidatorIT.java [hunk 3]
```diff
@@ -37,8 +37,7 @@ void testWrongContent() throws IOException, VerificationException {
         final VerificationException verificationException = assertThrows(VerificationException.class,
                 () -> verifier.executeGoal("project-keeper:verify"));
         final String output = verificationException.getMessage();
-        assertThat(output, containsString(
-                "[ERROR] E-PK-53: The dependencies.md file has a outdated content.\n" + "Expected content:\n"));
+        assertThat(output, containsString("[ERROR] E-PK-53: The dependencies.md file has a outdated content."));
```
[the remark this answers is not in the document]
Comment (jakobbraun) [reply src/test/java/com/exasol/projectkeeper/validators/dependencies/DependenciesValidatorIT.java:40]:
```suggestion
        assertThat(output, containsString("[ERROR] E-PK-53: The dependencies.md file has outdated content."));
```

File: src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java (hunk 1 above)
Comment (jakobbraun) [reply src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java:187]: It's a java try-with-reources. (see https://www.baeldung.com/java-try-with-resources)
It's an elegant way to close the git after the try block.

Comment (pj-spoelders) [reply src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java:187]: Ok thank you. I thought as much.
